///API 1 s1
GET http://localhost:3000/todos/?status=TO DO
###

///API 1 s2
GET http://localhost:3000/todos/?priority=HIGH
###

///API 1 s3
GET http://localhost:3000/todos/?priority=HIGH&status=INPROGRESS
###

///API 1 s4
GET http://localhost:3000/todos/?search_q=Buy
###

///API 1 s5
GET http://localhost:3000/todos/?category=WOR&status=DONE
###

///API 1 s6
GET http://localhost:3000/todos/?category=HOM
###

///API 1 s7
GET http://localhost:3000/todos/?category=LEARNING&priority=HIG
###

///API 2
GET http://localhost:3000/todos/1/
###

///API 3
GET http://localhost:3000/agenda/?date=2021--4
###


///API 4
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "HIGH",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}

###
///API 5 s1

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
  "status": "IN PROGRESS"
}

###
///API 5 s2

PUT http://localhost:3000/todos/:todoId/
Content-Type: application/json

{
  "priority": "HIGH"
}

###

///API 5 s3

PUT http://localhost:3000/todos/:todoId/
Content-Type: application/json
{
  "todo": "Clean the garden"
}

###

///API 5 s4

PUT http://localhost:3000/todos/:todoId/
Content-Type: application/json

{
  "category": "LEARNING"
}
###

///API 6 
DELETE http://localhost:3000/todos/:todoId/





